src/Entity/Tournament.php
<?php

namespace App\Entity;

use App\Repository\TournamentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TournamentRepository::class)]
class Tournament
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateStart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateEnd = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?float $playerNumber = null;

    #[ORM\Column]
    private ?float $tableNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'tournament', targetEntity: Game::class)]
    private Collection $games;

    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'tournaments')]
    private Collection $players;

    public function __construct()
    {
        $this->games = new ArrayCollection();
        $this->players = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTimeInterface $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->dateEnd;
    }

    public function setDateEnd(?\DateTimeInterface $dateEnd): self
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }


    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPlayerNumber(): ?float
    {
        return $this->playerNumber;
    }

    public function setPlayerNumber(float $playerNumber): self
    {
        $this->playerNumber = $playerNumber;

        return $this;
    }

    public function getTableNumber(): ?float
    {
        return $this->tableNumber;
    }

    public function setTableNumber(float $tableNumber): self
    {
        $this->tableNumber = $tableNumber;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }


    /**
     * @return Collection<int, Game>
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): self
    {
        if (!$this->games->contains($game)) {
            $this->games->add($game);
            $game->setTournament($this);
        }

        return $this;
    }

    public function removeGame(Game $game): self
    {
        if ($this->games->removeElement($game)) {
            // set the owning side to null (unless already changed)
            if ($game->getTournament() === $this) {
                $game->setTournament(null);
            }
        }

        return $this;
    }

    /**
     * @return User[]
     */
    public function getPlayers(): Collection
    {
        return $this->players;
    }

    public function addPlayer(User $player): self
    {
        if (!$this->players->contains($player)) {
            $this->players->add($player);
        }

        return $this;
    }

    public function removePlayer(User $player): self
    {
        $this->players->removeElement($player);

        return $this;
    }

    public function hasPlayer(User $player): bool
    {
        return $this->getPlayers()->contains($player);
    }

    public function getAvailablePlayerNumber(): int
    {
        return $this->getPlayerNumber() - count($this->getPlayers());
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'Il y a déjà un compte associé à cet email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $lastName = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $zipcode = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $city = null;

    #[ORM\Column(nullable: true)]
    private ?int $ranking = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Image]
    private ?string $image = null;

    #[ORM\OneToMany(mappedBy: 'playerOne', targetEntity: Game::class)]
    private Collection $gamesAsPlayerOne;

    #[ORM\OneToMany(mappedBy: 'playerTwo', targetEntity: Game::class)]
    private Collection $gamesAsPlayerTwo;

    #[ORM\ManyToMany(targetEntity: Tournament::class, mappedBy: 'players')]
    private Collection $tournaments;

    public function __construct()
    {
        $this->gamesAsPlayerOne = new ArrayCollection();
        $this->gamesAsPlayerTwo = new ArrayCollection();
        $this->tournaments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(?string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getRanking(): ?int
    {
        return $this->ranking;
    }

    public function setRanking(?int $ranking): self
    {
        $this->ranking = $ranking;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }

    /**
     * @return Collection<int, Game>
     */
    public function getGamesAsPlayerOne(): Collection
    {
        return $this->gamesAsPlayerOne;
    }

    public function addGameAsPlayerOne(Game $game): self
    {
        if (!$this->gamesAsPlayerOne->contains($game)) {
            $this->gamesAsPlayerOne->add($game);
            $game->setPlayerOne($this);
        }

        return $this;
    }

    public function removeGameAsPlayerOne(Game $game): self
    {
        if ($this->gamesAsPlayerOne->removeElement($game)) {
            // set the owning side to null (unless already changed)
            if ($game->getPlayerOne() === $this) {
                $game->setPlayerOne(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Game>
     */
    public function getGamesAsPlayerTwo(): Collection
    {
        return $this->gamesAsPlayerTwo;
    }

    public function addGameAsPlayerTwo(Game $game): self
    {
        if (!$this->gamesAsPlayerTwo->contains($game)) {
            $this->gamesAsPlayerTwo->add($game);
            $game->setPlayerTwo($this);
        }

        return $this;
    }

    public function removeGameAsPlayerTwo(Game $game): self
    {
        if ($this->gamesAsPlayerTwo->removeElement($game)) {
            // set the owning side to null (unless already changed)
            if ($game->getPlayerTwo() === $this) {
                $game->setPlayerTwo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tournament>
     */
    public function getTournaments(): Collection
    {
        return $this->tournaments;
    }

    public function addTournament(Tournament $tournament): self
    {
        if (!$this->tournaments->contains($tournament)) {
            $this->tournaments->add($tournament);
            $tournament->addPlayer($this);
        }

        return $this;
    }

    public function removeTournament(Tournament $tournament): self
    {
        if ($this->tournaments->removeElement($tournament)) {
            $tournament->removePlayer($this);
        }

        return $this;
    }

}

src/Controller/TournamentController.php
<?php

namespace App\Controller;

use App\Entity\Tournament;
use App\Form\TournamentType;
use App\Repository\TournamentRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\FileUploader;

#[Route('/tournament')]
class TournamentController extends AbstractController
{
    #[Route('/', name: 'app_tournament_index', methods: ['GET'])]
    public function index(TournamentRepository $tournamentRepository): Response
    {
        return $this->render('tournament/index.html.twig', [
            'tournaments' => $tournamentRepository->findAllFuture(),
        ]);
    }


    #[Route('/new', name: 'app_tournament_new', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request, FileUploader $fileUploader, TournamentRepository $tournamentRepository): Response
    {
        $tournament = new Tournament();
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /** @var UploadedFile $brochureFile */
            $brochureFile = $form->get('image')->getData();
            if ($brochureFile) {
                $brochureFileName = $fileUploader->upload($brochureFile);
                $tournament->setImage($brochureFileName);
            }
            $tournamentRepository->save($tournament, true);

            return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournament/new.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tournament_show', methods: ['GET'])]
    public function show(Tournament $tournament): Response
    {
        return $this->render('tournament/show.html.twig', [
            'tournament' => $tournament,
        ]);
    }

    #[Route('/{id}', name: 'app_tournament_showpast', methods: ['GET'])]
    public function showpast(Tournament $tournament): Response
    {
        return $this->render('tournament/showpast', [
            'tournament' => $tournament,
        ]);
    }

    #[Route('/{id}/participate', name: 'app_tournament_participate', methods: ['GET'])]
    public function participate(Tournament $tournament, TournamentRepository $tournamentRepository): Response
    {
        if ($tournament->hasPlayer($this->getUser())) {
            $tournament->removePlayer($this->getUser());
            $tournamentRepository->save($tournament, true);
        } else if ($tournament->getAvailablePlayerNumber() > 0) {
            $tournament->addPlayer($this->getUser());
            $tournamentRepository->save($tournament, true);
        } else {
            $this->addFlash('error', 'Il ne reste plus de place sur ce tournoi');
        }

        return $this->redirectToRoute('app_tournament_show', ['id' => $tournament->getId()]);
    }

    #[Route('/{id}/edit', name: 'app_tournament_edit', methods: ['GET', 'POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function edit(Request $request, Tournament $tournament, TournamentRepository $tournamentRepository): Response
    {
        $form = $this->createForm(TournamentType::class, $tournament);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $tournamentRepository->save($tournament, true);

            return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tournament/edit.html.twig', [
            'tournament' => $tournament,
            'form' => $form,
        ]);
    }


    #[Route('/{id}', name: 'app_tournament_delete', methods: ['POST'])]
    #[IsGranted('ROLE_ADMIN')]
    public function delete(Request $request, Tournament $tournament, TournamentRepository $tournamentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $tournament->getId(), $request->request->get('_token'))) {
            $tournamentRepository->remove($tournament, true);
        }

        return $this->redirectToRoute('app_tournament_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/tournament/_card.html.twig
<article class="bg-gray-50">
    <div class="flex">
        <div class="mr-8">
            <img src="{{ asset('uploads/' ~ tournament.image) }}" alt={{ "tournament.name" }};"
                 class="my-8 ml-16 lg:ml-8 w-28 h-28 rounded-lg">
        </div>
        <div>
            <h3 class="text-xl mt-12">{{ tournament.name }}</h3>
            <time datetime="{{ tournament.dateStart|date('d-m-Y H:i') }}">
                {{ tournament.dateStart|date('d-m-Y H:i') }}
            </time>
            <div class="mt-4">
                <button class="button ml-96 lg:ml-36">
                    <a href="{{ path('app_tournament_show', {'id': tournament.id}) }}">Détails et inscription <i
                                class="fa-sharp fa-solid fa-chevron-right"></i></a>
                </button>
            </div>
        </div>
    </div>
</article>

templates/tournament/_card2.html.twig
<article class="bg-gray-50">
    <div class="flex">
        <div class="mr-8">
            <img src="{{ asset('uploads/' ~ tournament.image) }}" alt={{ "tournament.name" }};"
                 class="mb-4 my-8 ml-16 lg:ml-8 w-28 h-28 rounded-lg">
        </div>
        <div>
            <h3 class="text-xl mt-12">{{ tournament.name }}</h3>
            <time datetime="{{ tournament.dateStart|date('d/m/Y H:i') }}">
                {{ tournament.dateStart|date('d/m/Y H:i') }}
            </time>
            <div class="mt-4">
                <button class="button ml-96 lg:ml-36">
                    <a href="{{ path('app_tournament_showpast', {'id': tournament.id}) }}">Détails<i
                                class="fa-sharp fa-solid fa-chevron-right"></i></a>
                </button>
            </div>
        </div>
    </div>
</article>

templates/tournament/_delete_form.html.twig
<form method="post" action="{{ path('app_tournament_delete', {'id': tournament.id}) }}"
      onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce tournoi ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tournament.id) }}">
    <button class="button font-normal">Supprimer</button>
</form>

templates/tournament/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un tournoi{% endblock %}

{% block body %}
    <div class="pb-36 px-12">
        <h1 class="text-5xl py-16">Modifier le tournoi</h1>

        {{ include('tournament/_form.html.twig', {'button_label': 'Valider'}) }}

        <button class="button">
            <a href="{{ path('app_tournament_index') }}">Retour à la liste</a></button>

        {{ include('tournament/_delete_form.html.twig') }}

    </div>

{% endblock %}

templates/tournament/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des tournois{% endblock %}

{% block body %}
    <div class="pb-36 px-12">
        <h1 class="text-5xl py-16">Les prochains tournois</h1>
        <div class="card lg:grid grid-cols-3">
            {% for tournament in tournaments %}
                <div class=>
                    <p><img src="{{ asset('uploads/' ~ tournament.image) }}" alt="{{ tournament.image }}"
                            class="object-cover h-96 w-96 rounded-lg mt-16 mb-12 ml-64 lg:ml-0"></p>
                </div>
                <div class="text-lg font-normal ml-12 lg:ml-2 lg:mt-20">
                    <p class="font-bold">{{ tournament.name }}</p>
                    <p>{{ tournament.dateStart ? tournament.dateStart|date('d/m/Y H:i') : '' }}</p>
                    <p>{{ tournament.description }}</p>
                    <p>{{ tournament.type }}</p>
                    <p>Nombre de joueurs :
                        {{ tournament.players|length }}
                        /
                        {{ tournament.playerNumber }}
                    </p>
                    <p>Nombre de table : {{ tournament.tableNumber }}</p>
                </div>


                <div class="flex flex-col lg:justify-center mt-8 lg:mt-12 ml-48 lg:ml-4">

                    <button class="button mr-48">
                        <a href="{{ path('app_tournament_show', {'id': tournament.id}) }}">Détails</a></button>

                    {% if (tournament.availablePlayerNumber > 0) %}
                    <button class="button mr-48">
                        <a href="{{ path('app_tournament_show', { 'id': tournament.id }) }}">Participer</a></button>
                    {% endif %}
                    {% if is_granted('ROLE_ADMIN') %}
                        <button class="button mr-48">
                            <a href="{{ path('app_tournament_edit', {'id': tournament.id}) }}">Modifier</a></button>
                    {% endif %}
                </div>

            {% else %}

                <p colspan="10">Pas de tournois prévus</p>

            {% endfor %}


        </div>
        {% if is_granted('ROLE_ADMIN') %}
            <button class="button ml-24 lg:ml-60 mt-12">
                <a href="{{ path('app_tournament_new') }}">Créer un tournoi</a>
            </button>
        {% endif %}
    </div>


{% endblock %}

templates/tournament/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'un nouveau tournoi{% endblock %}

{% block body %}
    <div class="mt-8">
        <h1 class="text-5xl py-16">Créer un nouveau tournoi</h1>
        <div class="flex justify-between">
            <div class="bg-white">
                {{ include('tournament/_form.html.twig') }}


            </div>
            <div class="grid grid-rows-3">
                <img src="{{ asset('uploads/feuille_de_match.jpg') }}" ; alt="feuille de match"
                     class="object-scale-down h-96 w-192 rounded row-span-2 mt-12 ml-8 blur-xs">
            </div>

    </div>
        <button class="button ml-8">
            <a href="{{ path('app_tournament_index') }}">Retour à la liste</a></button>


{% endblock %}

templates/tournament/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament{% endblock %}

{% block body %}

    <div class="mt-8">
    <h1 class="text-5xl py-16 px-8">{{ tournament.name }}</h1>

    <div class="text-3xl lg:mx-0 ">
    <div class="mx-24 lg:mx-0">
        <div class="lg:grid grid-cols-2">
            <div>
                <img src="{{ asset('uploads/' ~ tournament.image) }}" alt="{{ tournament.image }}"
                     class="object-contain h-48 w-96 flex-1 pb-4">

                <div class="font-normal">
                    <p>{{ tournament.description }}</p>
                    <p>
                        {{ tournament.dateStart|date('d/m/Y H:i') }}</p>

                    <p>{{ tournament.type }}</p>
                    <p>Nombre de joueurs : {{ tournament.playerNumber }}</p>
                    <p>Nombre de tables : {{ tournament.tableNumber }}</p>
                    <p>Liste des Participants :
                    <ul class="pl-48">
                        {% for player in tournament.players %}
                            <li class="pb-1">
                                {{ player.fullName }}
                            </li>
                        {% endfor %}
                    </ul>
                    </p>

                </div>

                {% if is_granted('ROLE_ADMIN') %}
                    <button class="button mr-4 mt-4">
                        <a href="{{ path('app_tournament_edit', {'id': tournament.id}) }}">Modifier</a>
                    </button>

                    {{ include('tournament/_delete_form.html.twig') }}

                {% endif %}

            </div>
            <div class="mt-4 lg:mt-16 lg:ml-4">
                {% if tournament.hasPlayer(app.user) %}
                    <div>
                        <button class="button">
                            <a href="{{ path('app_tournament_participate', {'id': tournament.id}) }}">
                                Se désinscrire
                            </a>
                        </button>
                    </div>
                    <div>
                {% elseif (tournament.availablePlayerNumber > 0) %}
                    <button class="button">
                        <a href="{{ path('app_tournament_participate', {'id': tournament.id}) }}">
                            S'inscrire
                        </a>
                    </button>
                    </div>
                {% endif %}
                <div>
                    <button class="button">
                        <a class="mt-2" href="{{ path('app_tournament_index') }}">Retour à la liste</a>
                    </button>
                </div>


            </div>


        </div>
    </div>


{% endblock %}

templates/tournament/showpast.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tournament{% endblock %}

{% block body %}

<div class="mt-8">
    <h1 class="text-5xl py-16 px-8">{{ tournament.name }}</h1>

    <div class="text-3xl lg:mx-0 ">
        <div class="mx-24 lg:mx-0">
            <div class="lg:grid grid-cols-2">
                <div>
                    <img src="{{ asset('uploads/' ~ tournament.image) }}" alt="{{ tournament.image }}"
                         class="object-contain h-48 w-96 flex-1 pb-4">

                    <div class="font-normal">
                        <p>{{ tournament.description }}</p>
                        <p>
                            {{ tournament.dateStart|date('d/m/Y H:i') }}</p>

                        <p>{{ tournament.type }}</p>
                        <p>Nombre de joueurs : {{ tournament.playerNumber }}</p>
                        <p>Nombre de tables : {{ tournament.tableNumber }}</p>
                        <p>Liste des Participants :
                        <ul class="pl-48">
                            {% for player in tournament.players %}
                                <li class="pb-1">
                                    {{ player.fullName }}
                                </li>
                            {% endfor %}
                        </ul>
                        </p>

                    </div>
                </div>
                <div>
                    <button class="button">
                        <a class="mt-2" href="{{ path('app_tournament_index') }}">Retour à la liste</a>
                    </button>
                </div>


            </div>
        </div>
    </div>


{% endblock %}